version: '3.7'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/ # persist data
    networks:
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./web/.env
    volumes:
      - ./web:/usr/src/app/
    depends_on:
      - database
    restart: always
    networks:
      - frontend
      - backend

  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
       - ./front:/app
       - /app/node_modules
    stdin_open: true
    depends_on:
      - web
    restart:  always
    networks:
      - frontend

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge
