version: '3.7'
services:
  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
       - ./front:/usr/src/app
       - /usr/src/app/node_modules
    networks:
      - backend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - ./web/.env.prod
    volumes:
      - ./web:/usr/src/app/
    depends_on:
      - database
    networks:
      - frontend
      - backend

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/ # persist data
    networks:
      - backend

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
